//COURSE TYPES
export const FETCH_COURSES_SUCCESS = "FETCH_COURSES_SUCCESS";
export const FETCH_COURSES_REQUEST = "FETCH_COURSES_REQUEST";
export const FETCH_COURSES_FAILURE = "FETCH_COURSES_FAILURE";


//EVENT TYPES
export const FETCH_EVENTS_SUCCESS = "FETCH_EVENTS_SUCCESS";
export const FETCH_EVENTS_REQUEST = "FETCH_EVENTS_REQUEST";
export const FETCH_EVENTS_FAILURE = "FETCH_EVENTS_FAILURE";


//LESSON TYPES
export const FETCH_LESSONS_SUCCESS = "FETCH_LESSONS_SUCCESS";
export const FETCH_LESSONS_REQUEST = "FETCH_LESSONS_REQUEST";
export const FETCH_LESSONS_FAILURE = "FETCH_LESSONS_FAILURE";

//ASSIGMENT TYPES
export const FETCH_ASSIGMENT_SUCCESS = "FETCH_ASSIGMENT_SUCCESS";
export const FETCH_ASSIGMENT_REQUEST = "FETCH_ASSIGMENT_REQUEST";
export const FETCH_ASSIGMENT_FAILURE = "FETCH_ASSIGMENT_FAILURE";