export const FETCH_COURSES = "FETCH_COURSES";
export const FETCH_EVENTS = "FETCH_EVENTS";
export const FETCH_COUNTRIES = 'FETCH_COUNTRIES';
export const FETCH_CITIES = 'FETCH_CITIES';
export const FETCH_STATES = 'FETCH_STATES';
export const SET_CELLS = 'SET_CELLS';
