//COURSE TYPES
export const FETCH_COURSES_SUCCESS = "FETCH_COURSES_SUCCESS";
export const FETCH_COURSES_REQUEST = "FETCH_COURSES_REQUEST";
export const FETCH_COURSES_FAILURE = "FETCH_COURSES_FAILURE";


//EVENT TYPES
export const FETCH_EVENTS_SUCCESS = "FETCH_EVENTS_SUCCESS";
export const FETCH_EVENTS_REQUEST = "FETCH_EVENTS_REQUEST";
export const FETCH_EVENTS_FAILURE = "FETCH_EVENTS_FAILURE";


//LESSON TYPES
export const FETCH_LESSONS_SUCCESS = "FETCH_LESSONS_SUCCESS";
export const FETCH_LESSONS_REQUEST = "FETCH_LESSONS_REQUEST";
export const FETCH_LESSONS_FAILURE = "FETCH_LESSONS_FAILURE";

//ASSIGMENT TYPES
export const FETCH_ASSIGMENT_SUCCESS = "FETCH_ASSIGMENT_SUCCESS";
export const FETCH_ASSIGMENT_REQUEST = "FETCH_ASSIGMENT_REQUEST";
export const FETCH_ASSIGMENT_FAILURE = "FETCH_ASSIGMENT_FAILURE";


//SERMON TYPES
export const FETCH_SERMON_SUCCESS = "FETCH_SERMON_SUCCESS";
export const FETCH_SERMON_REQUEST = "FETCH_SERMON_REQUEST";
export const FETCH_SERMON_FAILURE = "FETCH_SERMON_FAILURE";

//GPA CANDIDATE TYPES
export const FETCH_CANDIDATE_SUCCESS = "FETCH_CANDIDATE_SUCCESS";
export const FETCH_CANDIDATE_REQUEST = "FETCH_CANDIDATE_REQUEST";
export const FETCH_CANDIDATE_FAILURE = "FETCH_CANDIDATE_FAILURE";